import type { NextPage } from "next";
import Head from "next/head";

import { api, type RouterOutputs } from "~/utils/api";

function ItemCard(props: { item: RouterOutputs["item"]["all"][number] }) {
	return (
		<div>
			<pre>{JSON.stringify(props.item, null, 2)}</pre>
		</div>
	);
}

const Home: NextPage = () => {
	const itemQuery = api.item.all.useQuery();

	return (
		<>
			<Head>
				<title>Scavenger Hunt</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				{itemQuery.data ? (
					<div>
						{itemQuery.data?.length === 0 ? (
							<span>There are no items!</span>
						) : (
							<div>
								<div>
									{itemQuery.data?.map((p) => {
										return <ItemCard key={p.id} item={p} />;
									})}
								</div>
							</div>
						)}
					</div>
				) : (
					<p>Loading...</p>
				)}
			</main>
		</>
	);
};

export default Home;
