services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scavenger-hunt
    volumes:
      - postgres:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    networks:
      - postgres
 
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - postgres
 
volumes:
  postgres:

networks:
  postgres: