/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileEditIndexRouteImport } from './routes/profile/edit/index'
import { Route as HuntsCreateIndexRouteImport } from './routes/hunts/create/index'
import { Route as HuntsHuntIdIndexRouteImport } from './routes/hunts/$huntId/index'
import { Route as ApiCronHandlerIndexRouteImport } from './routes/api/cron-handler/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HuntsHuntIdLeaderboardIndexRouteImport } from './routes/hunts/$huntId/leaderboard/index'
import { Route as HuntsHuntIdItemsIndexRouteImport } from './routes/hunts/$huntId/items/index'
import { Route as HuntsHuntIdCollectIndexRouteImport } from './routes/hunts/$huntId/collect/index'
import { Route as HuntsHuntIdUsersUserIdIndexRouteImport } from './routes/hunts/$huntId/users/$userId/index'
import { Route as HuntsHuntIdItemsItemIdIndexRouteImport } from './routes/hunts/$huntId/items/$itemId/index'
import { Route as HuntsHuntIdCollectionItemsCollectionItemIdIndexRouteImport } from './routes/hunts/$huntId/collection-items/$collectionItemId/index'
import { Route as HuntsHuntIdItemsItemIdCollectIndexRouteImport } from './routes/hunts/$huntId/items/$itemId/collect/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditIndexRoute = ProfileEditIndexRouteImport.update({
  id: '/profile/edit/',
  path: '/profile/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsCreateIndexRoute = HuntsCreateIndexRouteImport.update({
  id: '/hunts/create/',
  path: '/hunts/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsHuntIdIndexRoute = HuntsHuntIdIndexRouteImport.update({
  id: '/hunts/$huntId/',
  path: '/hunts/$huntId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronHandlerIndexRoute = ApiCronHandlerIndexRouteImport.update({
  id: '/api/cron-handler/',
  path: '/api/cron-handler/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsHuntIdLeaderboardIndexRoute =
  HuntsHuntIdLeaderboardIndexRouteImport.update({
    id: '/hunts/$huntId/leaderboard/',
    path: '/hunts/$huntId/leaderboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HuntsHuntIdItemsIndexRoute = HuntsHuntIdItemsIndexRouteImport.update({
  id: '/hunts/$huntId/items/',
  path: '/hunts/$huntId/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsHuntIdCollectIndexRoute = HuntsHuntIdCollectIndexRouteImport.update({
  id: '/hunts/$huntId/collect/',
  path: '/hunts/$huntId/collect/',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsHuntIdUsersUserIdIndexRoute =
  HuntsHuntIdUsersUserIdIndexRouteImport.update({
    id: '/hunts/$huntId/users/$userId/',
    path: '/hunts/$huntId/users/$userId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HuntsHuntIdItemsItemIdIndexRoute =
  HuntsHuntIdItemsItemIdIndexRouteImport.update({
    id: '/hunts/$huntId/items/$itemId/',
    path: '/hunts/$huntId/items/$itemId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute =
  HuntsHuntIdCollectionItemsCollectionItemIdIndexRouteImport.update({
    id: '/hunts/$huntId/collection-items/$collectionItemId/',
    path: '/hunts/$huntId/collection-items/$collectionItemId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HuntsHuntIdItemsItemIdCollectIndexRoute =
  HuntsHuntIdItemsItemIdCollectIndexRouteImport.update({
    id: '/hunts/$huntId/items/$itemId/collect/',
    path: '/hunts/$huntId/items/$itemId/collect/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron-handler/': typeof ApiCronHandlerIndexRoute
  '/hunts/$huntId/': typeof HuntsHuntIdIndexRoute
  '/hunts/create/': typeof HuntsCreateIndexRoute
  '/profile/edit/': typeof ProfileEditIndexRoute
  '/hunts/$huntId/collect/': typeof HuntsHuntIdCollectIndexRoute
  '/hunts/$huntId/items/': typeof HuntsHuntIdItemsIndexRoute
  '/hunts/$huntId/leaderboard/': typeof HuntsHuntIdLeaderboardIndexRoute
  '/hunts/$huntId/collection-items/$collectionItemId/': typeof HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute
  '/hunts/$huntId/items/$itemId/': typeof HuntsHuntIdItemsItemIdIndexRoute
  '/hunts/$huntId/users/$userId/': typeof HuntsHuntIdUsersUserIdIndexRoute
  '/hunts/$huntId/items/$itemId/collect/': typeof HuntsHuntIdItemsItemIdCollectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron-handler': typeof ApiCronHandlerIndexRoute
  '/hunts/$huntId': typeof HuntsHuntIdIndexRoute
  '/hunts/create': typeof HuntsCreateIndexRoute
  '/profile/edit': typeof ProfileEditIndexRoute
  '/hunts/$huntId/collect': typeof HuntsHuntIdCollectIndexRoute
  '/hunts/$huntId/items': typeof HuntsHuntIdItemsIndexRoute
  '/hunts/$huntId/leaderboard': typeof HuntsHuntIdLeaderboardIndexRoute
  '/hunts/$huntId/collection-items/$collectionItemId': typeof HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute
  '/hunts/$huntId/items/$itemId': typeof HuntsHuntIdItemsItemIdIndexRoute
  '/hunts/$huntId/users/$userId': typeof HuntsHuntIdUsersUserIdIndexRoute
  '/hunts/$huntId/items/$itemId/collect': typeof HuntsHuntIdItemsItemIdCollectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron-handler/': typeof ApiCronHandlerIndexRoute
  '/hunts/$huntId/': typeof HuntsHuntIdIndexRoute
  '/hunts/create/': typeof HuntsCreateIndexRoute
  '/profile/edit/': typeof ProfileEditIndexRoute
  '/hunts/$huntId/collect/': typeof HuntsHuntIdCollectIndexRoute
  '/hunts/$huntId/items/': typeof HuntsHuntIdItemsIndexRoute
  '/hunts/$huntId/leaderboard/': typeof HuntsHuntIdLeaderboardIndexRoute
  '/hunts/$huntId/collection-items/$collectionItemId/': typeof HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute
  '/hunts/$huntId/items/$itemId/': typeof HuntsHuntIdItemsItemIdIndexRoute
  '/hunts/$huntId/users/$userId/': typeof HuntsHuntIdUsersUserIdIndexRoute
  '/hunts/$huntId/items/$itemId/collect/': typeof HuntsHuntIdItemsItemIdCollectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/profile/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/api/cron-handler/'
    | '/hunts/$huntId/'
    | '/hunts/create/'
    | '/profile/edit/'
    | '/hunts/$huntId/collect/'
    | '/hunts/$huntId/items/'
    | '/hunts/$huntId/leaderboard/'
    | '/hunts/$huntId/collection-items/$collectionItemId/'
    | '/hunts/$huntId/items/$itemId/'
    | '/hunts/$huntId/users/$userId/'
    | '/hunts/$huntId/items/$itemId/collect/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/profile'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/cron-handler'
    | '/hunts/$huntId'
    | '/hunts/create'
    | '/profile/edit'
    | '/hunts/$huntId/collect'
    | '/hunts/$huntId/items'
    | '/hunts/$huntId/leaderboard'
    | '/hunts/$huntId/collection-items/$collectionItemId'
    | '/hunts/$huntId/items/$itemId'
    | '/hunts/$huntId/users/$userId'
    | '/hunts/$huntId/items/$itemId/collect'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/profile/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/api/cron-handler/'
    | '/hunts/$huntId/'
    | '/hunts/create/'
    | '/profile/edit/'
    | '/hunts/$huntId/collect/'
    | '/hunts/$huntId/items/'
    | '/hunts/$huntId/leaderboard/'
    | '/hunts/$huntId/collection-items/$collectionItemId/'
    | '/hunts/$huntId/items/$itemId/'
    | '/hunts/$huntId/users/$userId/'
    | '/hunts/$huntId/items/$itemId/collect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronHandlerIndexRoute: typeof ApiCronHandlerIndexRoute
  HuntsHuntIdIndexRoute: typeof HuntsHuntIdIndexRoute
  HuntsCreateIndexRoute: typeof HuntsCreateIndexRoute
  ProfileEditIndexRoute: typeof ProfileEditIndexRoute
  HuntsHuntIdCollectIndexRoute: typeof HuntsHuntIdCollectIndexRoute
  HuntsHuntIdItemsIndexRoute: typeof HuntsHuntIdItemsIndexRoute
  HuntsHuntIdLeaderboardIndexRoute: typeof HuntsHuntIdLeaderboardIndexRoute
  HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute: typeof HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute
  HuntsHuntIdItemsItemIdIndexRoute: typeof HuntsHuntIdItemsItemIdIndexRoute
  HuntsHuntIdUsersUserIdIndexRoute: typeof HuntsHuntIdUsersUserIdIndexRoute
  HuntsHuntIdItemsItemIdCollectIndexRoute: typeof HuntsHuntIdItemsItemIdCollectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit/': {
      id: '/profile/edit/'
      path: '/profile/edit'
      fullPath: '/profile/edit/'
      preLoaderRoute: typeof ProfileEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/create/': {
      id: '/hunts/create/'
      path: '/hunts/create'
      fullPath: '/hunts/create/'
      preLoaderRoute: typeof HuntsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/': {
      id: '/hunts/$huntId/'
      path: '/hunts/$huntId'
      fullPath: '/hunts/$huntId/'
      preLoaderRoute: typeof HuntsHuntIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron-handler/': {
      id: '/api/cron-handler/'
      path: '/api/cron-handler'
      fullPath: '/api/cron-handler/'
      preLoaderRoute: typeof ApiCronHandlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/leaderboard/': {
      id: '/hunts/$huntId/leaderboard/'
      path: '/hunts/$huntId/leaderboard'
      fullPath: '/hunts/$huntId/leaderboard/'
      preLoaderRoute: typeof HuntsHuntIdLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/items/': {
      id: '/hunts/$huntId/items/'
      path: '/hunts/$huntId/items'
      fullPath: '/hunts/$huntId/items/'
      preLoaderRoute: typeof HuntsHuntIdItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/collect/': {
      id: '/hunts/$huntId/collect/'
      path: '/hunts/$huntId/collect'
      fullPath: '/hunts/$huntId/collect/'
      preLoaderRoute: typeof HuntsHuntIdCollectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/users/$userId/': {
      id: '/hunts/$huntId/users/$userId/'
      path: '/hunts/$huntId/users/$userId'
      fullPath: '/hunts/$huntId/users/$userId/'
      preLoaderRoute: typeof HuntsHuntIdUsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/items/$itemId/': {
      id: '/hunts/$huntId/items/$itemId/'
      path: '/hunts/$huntId/items/$itemId'
      fullPath: '/hunts/$huntId/items/$itemId/'
      preLoaderRoute: typeof HuntsHuntIdItemsItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/collection-items/$collectionItemId/': {
      id: '/hunts/$huntId/collection-items/$collectionItemId/'
      path: '/hunts/$huntId/collection-items/$collectionItemId'
      fullPath: '/hunts/$huntId/collection-items/$collectionItemId/'
      preLoaderRoute: typeof HuntsHuntIdCollectionItemsCollectionItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$huntId/items/$itemId/collect/': {
      id: '/hunts/$huntId/items/$itemId/collect/'
      path: '/hunts/$huntId/items/$itemId/collect'
      fullPath: '/hunts/$huntId/items/$itemId/collect/'
      preLoaderRoute: typeof HuntsHuntIdItemsItemIdCollectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronHandlerIndexRoute: ApiCronHandlerIndexRoute,
  HuntsHuntIdIndexRoute: HuntsHuntIdIndexRoute,
  HuntsCreateIndexRoute: HuntsCreateIndexRoute,
  ProfileEditIndexRoute: ProfileEditIndexRoute,
  HuntsHuntIdCollectIndexRoute: HuntsHuntIdCollectIndexRoute,
  HuntsHuntIdItemsIndexRoute: HuntsHuntIdItemsIndexRoute,
  HuntsHuntIdLeaderboardIndexRoute: HuntsHuntIdLeaderboardIndexRoute,
  HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute:
    HuntsHuntIdCollectionItemsCollectionItemIdIndexRoute,
  HuntsHuntIdItemsItemIdIndexRoute: HuntsHuntIdItemsItemIdIndexRoute,
  HuntsHuntIdUsersUserIdIndexRoute: HuntsHuntIdUsersUserIdIndexRoute,
  HuntsHuntIdItemsItemIdCollectIndexRoute:
    HuntsHuntIdItemsItemIdCollectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
